### ISSUE TITLE
[Regression] Delayed audio notes with certain games (ex: Donkey Kong Land)

### ISSUE THREAD

**Issue by Ryunam** [libretro/SameBoy#62]
I have noticed an audio-related regression with the latest Sameboy core as it is currently downloaded from the buildbot. I only reproduced this with one game so far (Donkey Kong Land), but it could affect other titles.

When playing Donkey Kong Land and idling on the world map, you can hear that the melody of the music plays with a noticeable delay compared to the other instruments in the same track.

This does not occur on the latest standalone version of Sameboy for Windows. It also does not happen with older versions of the Sameboy core, prior to the latest resync to upstream. 

Check here a quick recording for comparison's sake:

**With current master (d478d3e)**
https://user-images.githubusercontent.com/17614150/113507214-73083100-9549-11eb-96dc-2ed71a849fad.mp4

**With an older version prior to the resync (907cb96)**
https://user-images.githubusercontent.com/17614150/113507312-f3c72d00-9549-11eb-8010-78f669b30368.mp4

**Comment by RokkumanX** [comment]
@Ryunam 

OK, I spent some serious time with this and as I said in the pull request earlier today I can confirm what you are experiencing 100%

I had to build the older core myself since there were no other option available.

Indeed there are no issues with 0.13.6 but with the latest official Libretro core and my own built 0.14.3 core there are.

The older version you pointed to is from January 10th and the latest version is from March 14th which means the regression have to be somewhere between those two dates, all newer ones can be ruled out since it happens on the very latest 0.14.3 version.

I have really tried to find the specific commit, experimenting with different builds I have made that could be related to audio but so far I have come out empty handed and it all sounds the same and broken.

@liji32

Do you know which commit (audio related) between January 10th and March 14th that could have broke the sound in Donkey Kong Land (Super Donkey Kong GB) for the Libretro core?

**Comment by RokkumanX** [comment]
I have spent some of this morning trying to compile different versions between the dates posted above and I have not been successful at all and on top of that a bunch of NUL files were created which are really difficult to remove from Windows.

I can build the latest official Libretro core (0.14.2), the January 10th one (0.13.6) and the one from my repository containing all the updates (0.14.3) with no issues at all.

I'm not feeling for going through all individual commits right now in order to find one that builds, it would take quite some time.

An unrelated note is that I tried the game with bsnes since the Super Game Boy part uses SameBoy and yes the audio works fine there but it's 0.13.6 so that's expected.

This makes me really sad, I was about to switch to SameBoy permanently but it seems every time I'm trying there is this one thing that breaks it and holds me back from going with it.

Not trying to be ungrateful or anything and I'm sorry this went on longer then expected but going through commit after commit really wears you out after a while.

**Comment by RokkumanX** [comment]
This is a list of commits from March 14th to January 10th that are audio related:

- [ Fix an APU regression that caused some games in DMG mode to play in the wrong pitch](https://github.com/libretro/SameBoy/commit/ea97c1dc0b596204ba546583e8912ae8b7073865)
- [Fix a sweep regression in DMG/SGB mode and CGB-C mode](https://github.com/libretro/SameBoy/commit/1fdb4f09b44731b24a21c66235d554bfd7d185e8)
- [ Redo the volume envelope with better timings, locking emulation and zombie mode edge cases](https://github.com/libretro/SameBoy/commit/4c05ebcea60368ffda2bbe96104182031f297f7b)
- [Emulate volume envelope locking](https://github.com/libretro/SameBoy/commit/393269ae1f9be91edaaa605ce9b55ca6f4c3fb68)
- [Improved emulation of the volume envelope](https://github.com/libretro/SameBoy/commit/6d2d88648e6bbe81cd986a0186dad85e80f42909)
- [Further accuracy improvements to the audio envelope](https://github.com/libretro/SameBoy/commit/d50fdc52eacb8b907d0ed0c3529ff52dda2f6127)
- [More correct emulation of manual clocking of channels 1 and 2](https://github.com/libretro/SameBoy/commit/8809d8ac2f16d160d3989d9ac6394afe2e39ba17)
- [Rename UNROLL to unrolled (unrolled for)](https://github.com/libretro/SameBoy/commit/71c88323b7d1a4f69cc41411d11429cf1bfa9cb1)
- [ Improved emulation of the NRx2 write glitch (Zombie mode) on models prior to CGB-D](https://github.com/libretro/SameBoy/commit/95051d1c1c6e463505a280854c9ce2aeb2f49788)
- [Emulation of NR43 bit 3 glitch on CGB-C and older](https://github.com/libretro/SameBoy/commit/2d766982799b03c4333b6784593c903f54d55e45)
- [Oops, that was reversed](https://github.com/libretro/SameBoy/commit/d67580c96405c7ee07168b3dcedd7a29d4b18041)
- [More NR43 obscurities](https://github.com/libretro/SameBoy/commit/ef9671010b0ae181e6c65ff4c228d2a06f3ee6d9)
- [Timing fix](https://github.com/libretro/SameBoy/commit/13a1e9d332e5fce328e9850da8f94215897e7e87)
- [Revert "Further NR43 write glitch emulation" for now](https://github.com/libretro/SameBoy/commit/0056cc2d61448e9b3842f27449da4b62620f3adc)

One or more of these could be the culprit which made the regression but only @LIJI32 would know for sure.

**Comment by RokkumanX** [comment]
> This does not occur on the latest standalone version of Sameboy for Windows.

This statement made me very confused so I had to check it out and it's definitely not true, it happens on all 0.14.x versions of the standalone SameBoy emulator also, at least from my end.

Furthermore 0.13.6 is the last version whether it be the standalone, Libretro or bsnes version that sounds good.
By good I mean it sounds like it should and how it sounds in Gambatte and bgb.

**Comment by RokkumanX** [comment]
I made an issue upstream since it happens on the standalone also, and if it gets fixed there it will be fixed here too.
https://github.com/LIJI32/SameBoy/issues/390

Don't think there's more we can do at this point @Ryunam 

Have a good day for now!

**Comment by Ryunam** [comment]
Oh, interesting, I was pretty sure that it was not occurring on standalone. In that case it was definitely the right thing to post an issue report on the upstream repository. Let’s wait for an update.

Thank you for taking the time to investigate this so thoroughly!

**Comment by RokkumanX** [comment]
No problem, I uploaded .WAV files in that issue taken from the standalone versions of 0.13.6 and 0.14.x
And there is no doubt, the issue is present in the standalone versions.

**Comment by Ryunam** [comment]
This was fixed upstream with https://github.com/LIJI32/SameBoy/commit/b4709fd66bd986a5c32b423b317e74ab7a96470d (thanks!), so as soon as that commit is pulled and merged into the libretro core repository I'll close the issue.

**Comment by RokkumanX** [comment]
@Ryunam 

Here is Santa Claus with latest build with the Donkey Kong fix!!!

[sameboy_libretro.zip](https://github.com/libretro/SameBoy/files/6682512/sameboy_libretro.zip)

My Pull request have been updated with all latest SameBoy updates, it's a shame it will probably never get merged, I have reached out to the Libretro Forums but nothing have happened since.

Why doesn't they just merge this already????

**Comment by Ryunam** [comment]
Thank you for building the core with the latest additions. :) Speaking of the merge timing, please note that the team always has quite a lot on their plate, so any new contribution submitted to any of the libretro cores requires a variable amount of time to be properly evaluated, tested and approved. It's important to be patient, there's never really any intention to block a PR just for the sake of not merging things.

I will now test the newly-compiled core to see if I spot any issues, especially with respect to specific features such as Runahead support and savestate compatibility. I am sure everything will work perfectly fine as per your tests, but let me do this quick check and I'll make sure to report back my findings in the PR thread.

**Comment by RokkumanX** [comment]
Hi @Ryunam 

Everything works well and have been merged, time to close the issue?

**Comment by Ryunam** [comment]
Thank you for reminding me of this! Yes, we can close this for good.
