### ISSUE TITLE
Update to 0.14.3

### ISSUE THREAD

**Issue by RobLoach** [libretro/SameBoy#64]
https://github.com/LIJI32/SameBoy/releases/tag/v0.14.3

From r5...

you think it's possible with the new infra to add a build step that takes care of SameBoy's BIOS?

It would be something like:
1) Clone https://github.com/gbdev/rgbds
2) Build rgbds
3) Clone https://github.com/LIJI32/SameBoy
4) Use rgbds to build everything in https://github.com/LIJI32/SameBoy/tree/master/BootROMs
5) Build Sameboy

**Comment by RokkumanX** [comment]
I made a [pull request](https://github.com/libretro/SameBoy/pull/63) 11 days ago in hope to update the core.

But I have not received any response of it at all so I have no idea what is going to happen with it.

Since I use specific and customized core settings I have built it myself with the same pull request and it works perfectly.

**Comment by RokkumanX** [comment]
I made a [pull request](https://github.com/libretro/SameBoy/pull/65) in hope to update the core.

@twinaphex 

Would it be possible to merge?

**Comment by RokkumanX** [comment]
So yeah, there is a pull request ready to merge if you want to have SameBoy updated with latest changes.
Any interest????

**Comment by RobLoach** [comment]
This is most excellent! Thanks a lot @RokkumanX. I'd be happy to test this later on. 👍 .... Closing this for now so we can discuss in the PR.
