### ISSUE TITLE
Can't update the core anymore because of merge conflicts

### ISSUE THREAD

**Issue by RokkumanX** [libretro/SameBoy#80]
So yeah, things used to be so simple a couple of months ago when you could compare repositories, create a pull request and merge it relatively quickly.

I have been wanting to [update](https://github.com/RokkumanX/SameBoy/pull/27) the Libretro core with all the latest changes but for the first time I've hit a roadblock, "This branch has conflicts that must be resolved"

I have no idea what commit/commits it's referring to because it's being very cryptic and I can't do anything about it from here via the browser version of GitHub.

I also have no idea how to use the command line or knows what the GitHub desktop is, so here everything have halted I'm afraid and don't know how to proceed from here.

**Comment by 13spacemen** [comment]
@RokkumanX do you have discord?

**Comment by Ryunam** [comment]
I have started work on a proper update. It seems the reason for the merge conflicts you have encountered is that both upstream and downstream have separately implemented several edits to the libretro-specific files, especially the ones related to the core options. This is causing a mismatch here when fetching the most recent changes.

I will try to first incorporate the needed changes here and then also submit a PR upstream, so that the two repositories can be brought in line with each other again.

**Comment by RokkumanX** [comment]
Sorry for the late reply but thank you very much for this :)

**Comment by Ryunam** [comment]
No problem at all!
